import {Inter} from "next/font/google"
import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const fontPadrao = Inter({ subsets: ['latin'] })

export default function RootLayout({children}: { children: React.ReactNode}) {
    return (
      <html lang="pt-br" className={fontPadrao.className}>
        <body>{children}</body>
      </html>
    )
}
